#
# Service for the application cluster
#
apiVersion: v1
kind: Service
metadata:
  name: ef-kubernetes-app
  labels:
    app: ef-kubernetes-app
spec:
  selector:
    app: ef-kubernetes-app
  clusterIP: None
---

#
# application cluster as a stateful set
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ef-kubernetes-app
spec:
  selector:
    matchLabels:
      app: ef-kubernetes-app
  serviceName: "ef-kubernetes-app"
  #
  # initially 3 eventflow nodes in the cluster
  # can be scaled up or down
  #
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: ef-kubernetes-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ef-kubernetes-app
          #
          # docker image to use
          #
          image: ef-kubernetes-app:1.0.0
          imagePullPolicy: Never
          #
          # Share application logs to docker console
          #
          tty: true
          #
          # use heathcheck API to test for readiness
          #
          readinessProbe:
            httpGet:
              path: /healthcheck/v1/status
              port: 8008
              #
              # need to specify basic authentication
              # this use the username and password that the eventflow
              # node was started with
              #
              httpHeaders:
              - name: Authorization
                value: Basic dGliY286dGliY28=
            initialDelaySeconds: 60
            periodSeconds: 10
          #
          # use heathcheck API to test for liveness
          # should 
          #
          livenessProbe:
            httpGet:
              path: /healthcheck/v1/status
              port: 8008
              #
              # need to specify basic authentication
              # this use the username and password that the eventflow
              # node was started with
              #
              httpHeaders:
              - name: Authorization
                value: Basic dGliY286dGliY28=
            initialDelaySeconds: 60
            periodSeconds: 10
      #
      # the default DNS policy doesn't allow for full name
      # resolution by hostname, so we create our own and
      # specify the search domain name
      #
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - ef-kubernetes-app.default.svc.cluster.local
        options:
          - name: ndots
            value: "5"
